export const Playlist = [
{
    id: "0",
    artist: "Johann Pachelbel",
    title: "Canon in D",
    category: "Classical",
    song: "/audio/canon.mp3",
    cover: "/images/canon.jpg",
},
{
    id: "1",
    artist: "Felix Mendelssohn",
    title: "Wedding March",
    category: "Classical",
    song: "/audio/wedding.mp3",
    cover: "/images/weddingMarch.jpg",
},
{
    id: "2",
    artist: "Ozzy Osbourne",
    title: "Crazy Train",
    category: "Rock",
    song: "/audio/crazyTrain.mp3",
    cover: "/images/crazytrain.jpg",
},
{
    id: "3",
    artist: "Queen",
    title: "Bohemian Rhapsody",
    category: "Rock",
    song: "/audio/queen.mp3",
    cover: "/images/queen.jpg",
},
{
    id: "4",
    artist: "Migos ft NBA Youngboy",
    title: "Need It",
    category: "Hip-Hop",
    song: "/audio/needit.mp3",
    cover: "/images/needit.png",
},
{
    id: "5",
    artist: "Jim Jones",
    title: "We Fly High",
    category: "Hip-Hop",
    song: "/audio/ballin.mp3",
    cover: "/images/ballin.jpg",
},
{
    id: "6",
    artist: "Nirvana",
    title: "Smells Like Teen Spirit",
    category: "Alternative",
    song: "/audio/nirvana.mp3",
    cover: "/images/nirvana.jfif",
},
{
    id: "7",
    artist: "Finger 11",
    title: "Paralyzer",
    category: "Alternative",
    song: "/audio/paralyzer.mp3",
    cover: "/images/finger11.jfif",
},
{
    id: "8",
    artist: "Kid Rock ft Sheryl Crow",
    title: "Picture",
    category: "Country",
    song: "/audio/picture.mp3",
    cover: "/images/picture.jpg",
},
{
    id: "9",
    artist: "Josh Turner",
    title: "Canon in D",
    category: "Country",
    song: "/audio/yourman.mp3",
    cover: "/images/yourman.jfif",
},
{
    id: "10",
    artist: "Doja Cat",
    title: "Say So",
    category: "Pop",
    song: "/audio/sayso.mp3",
    cover: "/images/doja.png",
},
{
    id: "11",
    artist: "A-ha",
    title: "Take On Me",
    category: "Pop",
    song: "/audio/takeonme.mp3",
    cover: "/images/takeon.jpg",
},
{
    id: "12",
    artist: "Chris Brown",
    title: "Tempo",
    category: "RnB",
    song: "/audio/tempo.mp3",
    cover: "/images/tempo.jpg",
},
{
    id: "13",
    artist: "Tory Lanez",
    title: "Say My Name",
    category: "RnB",
    song: "/audio/torySMN.mp3",
    cover: "/images/smn.jpg",
},

]